server:
  port: 8666

spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/eudaimonia_db
    username: eudaimonia_user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

otel:
  sampler:
    probability: 1.0
  exporter:
    otlp:
      endpoint: http://localhost:4318
      protocol: http/protobuf
  logs:
    exporter: none
  traces:
    exporter: otlp
  metrics:
    exporter: none
  service:
    name: human-api


management:
  tracing:
    enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, info, prometheus, metrics, loggers, logfile
      cors:
        allowed-origins: '*'
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
