openapi: 3.0.1
info:
  title: Human Simulation API
  version: 1.0.0


tags:
  - name: Human

paths:
  /api/humans:
    get:
      tags:
        - Human
      summary: List all humans
      operationId: getAllHumans
      responses:
        '200':
          description: human list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Human'
    post:
      tags:
        - Human
      summary: add a new human
      operationId: addHuman
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Human'
      responses:
        '200':
          description: Human added

components:
  schemas:
    Human:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        birthDate:
          type: string
          format: date
      required:
        - firstName
        - lastName
