version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: eudaimonia-postgres
    environment:
      POSTGRES_DB: eudaimonia_db
      POSTGRES_USER: eudaimonia_user
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eudaimonia_user -d eudaimonia_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local 